In [31]:
#read csvs

import pandas as pd

dataNoTemplate = pd.read_csv("dospert_llm_scores_all_candidates.csv")
dataWithTemplate = pd.read_csv("dospert_llm_scores_chatstyle.csv")
dataWithTemplate

,human_number,1,2,3,4,5,item,participant,flipped,experiment
0,2,-8.164062,-8.437500,-7.863281,-8.429688,-7.988281,1,65073301,yes,DOSPERT scale
1,2,-10.132812,-10.234375,-9.617188,-10.210938,-9.351562,2,65073301,yes,DOSPERT scale
2,5,-15.265625,-15.671875,-16.015625,-15.882812,-15.335938,3,65073301,yes,DOSPERT scale
3,4,-15.796875,-15.843750,-16.078125,-16.234375,-14.695312,4,65073301,yes,DOSPERT scale
4,2,-13.914062,-14.039062,-12.984375,-13.937500,-13.281250,5,65073301,yes,DOSPERT scale
...,...,...,...,...,...,...,...,...,...,...
75,4,-13.320312,-13.406250,-13.539062,-13.750000,-13.281250,36,64022901,no,DOSPERT scale
76,4,-13.078125,-13.132812,-13.304688,-13.453125,-13.039062,37,64022901,no,DOSPERT scale
77,5,-13.062500,-13.421875,-13.593750,-13.601562,-13.414062,38,64022901,no,DOSPERT scale
78,2,-13.328125,-13.515625,-13.335938,-13.632812,-13.023438,39,64022901,no,DOSPERT scale
79,2,-11.687500,-11.914062,-11.531250,-11.820312,-11.328125,40,64022901,no,DOSPERT scale

In [32]:
dataWithTemplate.columns

Index(['human_number', '1', '2', '3', '4', '5', 'item', 'participant',
       'flipped', 'experiment'],
      dtype='object')

In [33]:
dataWithTemplate

,human_number,1,2,3,4,5,item,participant,flipped,experiment
0,2,-8.164062,-8.437500,-7.863281,-8.429688,-7.988281,1,65073301,yes,DOSPERT scale
1,2,-10.132812,-10.234375,-9.617188,-10.210938,-9.351562,2,65073301,yes,DOSPERT scale
2,5,-15.265625,-15.671875,-16.015625,-15.882812,-15.335938,3,65073301,yes,DOSPERT scale
3,4,-15.796875,-15.843750,-16.078125,-16.234375,-14.695312,4,65073301,yes,DOSPERT scale
4,2,-13.914062,-14.039062,-12.984375,-13.937500,-13.281250,5,65073301,yes,DOSPERT scale
...,...,...,...,...,...,...,...,...,...,...
75,4,-13.320312,-13.406250,-13.539062,-13.750000,-13.281250,36,64022901,no,DOSPERT scale
76,4,-13.078125,-13.132812,-13.304688,-13.453125,-13.039062,37,64022901,no,DOSPERT scale
77,5,-13.062500,-13.421875,-13.593750,-13.601562,-13.414062,38,64022901,no,DOSPERT scale
78,2,-13.328125,-13.515625,-13.335938,-13.632812,-13.023438,39,64022901,no,DOSPERT scale
79,2,-11.687500,-11.914062,-11.531250,-11.820312,-11.328125,40,64022901,no,DOSPERT scale

In [34]:
# Get the column (1-5) with the largest value in each row
dataWithTemplate['max_column'] = dataWithTemplate[["1", "2", "3", "4", "5"]].idxmax(axis=1)
dataNoTemplate['max_column'] = dataNoTemplate[["1", "2", "3", "4", "5"]].idxmax(axis=1)

dataNoTemplate

,item,human_number,1,2,3,4,5,participant,flipped,experiment,max_column
0,1,2,-8.054688,-7.585938,-5.828125,-7.273438,-8.210938,65073301,yes,DOSPERT scale,3
1,2,2,-13.046875,-12.898438,-12.484375,-13.101562,-12.164062,65073301,yes,DOSPERT scale,5
2,3,5,-16.906250,-17.046875,-17.500000,-18.078125,-17.125000,65073301,yes,DOSPERT scale,1
3,4,4,-17.265625,-16.593750,-16.906250,-17.765625,-15.929688,65073301,yes,DOSPERT scale,5
4,5,2,-14.757812,-14.703125,-14.890625,-15.429688,-14.585938,65073301,yes,DOSPERT scale,5
...,...,...,...,...,...,...,...,...,...,...,...
75,36,4,-15.453125,-15.265625,-15.843750,-16.343750,-15.414062,64022901,no,DOSPERT scale,2
76,37,4,-14.914062,-14.734375,-15.359375,-15.851562,-14.679688,64022901,no,DOSPERT scale,5
77,38,5,-14.359375,-14.820312,-15.648438,-15.984375,-15.218750,64022901,no,DOSPERT scale,1
78,39,2,-13.164062,-13.460938,-13.539062,-13.484375,-12.984375,64022901,no,DOSPERT scale,5
79,40,2,-13.414062,-13.656250,-13.953125,-13.945312,-13.445312,64022901,no,DOSPERT scale,1

In [35]:
df1 = dataWithTemplate[['max_column']].rename(columns={'max_column': 'max_column_template'})
df2 = dataNoTemplate[['max_column']].rename(columns={'max_column': 'max_column_no_template'})

# Concatenate them side by side
merged_df = pd.concat([df1, df2], axis=1)
merged_df["same"] = merged_df["max_column_template"] == merged_df["max_column_no_template"]
merged_df["same"].sum()

58

# Analyse Variance and differences between no chat and chat in BART Task

In [11]:
import pandas as pd

BART_WITH_CHAT = pd.read_csv("outputs/SmolLM2-1.7B-Instruct_Bart_Prompting_results.csv")
BART_NO_CHAT = pd.read_csv("outputs/SmolLM2-1.7B-Instruct_Bart_Prompting_noChatTemplate_results.csv")

In [12]:
summary_stats_chat = BART_WITH_CHAT[["log_prob_pump", "log_prob_stop"]].describe()
summary_stats_no_chat = BART_NO_CHAT[["log_prob_pump", "log_prob_stop"]].describe()
summary_stats_df = pd.concat([summary_stats_chat, summary_stats_no_chat], axis=1)
summary_stats_df

       log_prob_pump  log_prob_stop  log_prob_pump  log_prob_stop
count   11787.000000   11787.000000   11787.000000   11787.000000
mean      -23.184796     -23.980450      -0.003386     -11.250421
std         6.968978       7.259817       0.034800       2.896061
min       -35.000000     -38.000000      -1.359375     -18.625000
25%       -28.000000     -28.500000      -0.000423     -13.187500
50%       -25.750000     -26.750000      -0.000146     -11.687500
75%       -21.875000     -23.500000      -0.000059      -9.687500
max       -10.750000     -10.750000      -0.000005      -0.400391

In [13]:
# Get the column with the largest value in each row
BART_WITH_CHAT['max_column'] = BART_WITH_CHAT[["log_prob_pump", "log_prob_stop"]].idxmax(axis=1)
BART_NO_CHAT['max_column'] = BART_NO_CHAT[["log_prob_pump", "log_prob_stop"]].idxmax(axis=1)

In [14]:
df1 = BART_WITH_CHAT[['max_column']].rename(columns={'max_column': 'max_column_template'})
df2 = BART_NO_CHAT[['max_column']].rename(columns={'max_column': 'max_column_no_template'})

# Concatenate them side by side
merged_df = pd.concat([df1, df2], axis=1)
merged_df["same"] = merged_df["max_column_template"] == merged_df["max_column_no_template"]
same = merged_df["same"].sum()
complete_data = len(merged_df)

(same * 100)/complete_data

72.51208959022652

In [15]:
# ---- Calc Probability for human answer normalized over answer alternatives ----
import numpy as np

logprob_cols = ["log_prob_pump", "log_prob_stop"]

# Step 1: Convert log-probs to probabilities
# We exponentiate the log probabilities
prob_matrix_WITH_CHAT = np.exp(BART_WITH_CHAT[logprob_cols].values)
prob_matrix_NO_CHAT = np.exp(BART_NO_CHAT[logprob_cols].values)


# Step 2: Normalize so that each row sums to 1
prob_matrix_WITH_CHAT = prob_matrix_WITH_CHAT / prob_matrix_WITH_CHAT.sum(axis=1, keepdims=True)
prob_matrix_NO_CHAT = prob_matrix_NO_CHAT / prob_matrix_NO_CHAT.sum(axis=1, keepdims=True)

# Step 3: Add new columns for each normalized probability
for i, col in enumerate(logprob_cols):
    BART_WITH_CHAT[f'prob_{col}'] = prob_matrix_WITH_CHAT[:, i]
    BART_NO_CHAT[f'prob_{col}'] = prob_matrix_NO_CHAT[:, i]


# Step 4: Extract probability of actual human choice
# 'human_number' is 1-indexed; need to subtract 1 for zero-based indexing

In [18]:
summary_stats_chat = BART_WITH_CHAT[["prob_log_prob_pump", "prob_log_prob_stop"]].describe()
summary_stats_no_chat = BART_NO_CHAT[["prob_log_prob_pump", "prob_log_prob_stop"]].describe()
summary_stats_df = pd.concat([summary_stats_chat, summary_stats_no_chat], axis=1)
summary_stats_df

,prob_log_prob_pump,prob_log_prob_stop,prob_log_prob_pump,prob_log_prob_stop
count,11787.000000,11787.000000,11787.000000,1.178700e+04
mean,0.621226,0.378774,0.997672,2.328476e-03
std,0.276036,0.276036,0.021745,2.174502e-02
min,0.053403,0.000335,0.293404,8.152147e-09
25%,0.407333,0.095349,0.999938,1.873931e-06
50%,0.500000,0.500000,0.999992,8.399530e-06
75%,0.904651,0.592667,0.999998,6.210318e-05
max,0.999665,0.946597,1.000000,7.065955e-01